'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3662
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<System.Data.Linq.Mapping.DatabaseAttribute(Name:="HPB_Logistics")>  _
Partial Public Class HPBDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.CDCData.My.MySettings.Default.HPB_LogisticsConnectionString1, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property vw_BT_Inv_Hdrs() As System.Data.Linq.Table(Of vw_BT_Inv_Hdr)
		Get
			Return Me.GetTable(Of vw_BT_Inv_Hdr)
		End Get
	End Property
	
	Public ReadOnly Property vw_BT_Inv_Dtls() As System.Data.Linq.Table(Of vw_BT_Inv_Dtl)
		Get
			Return Me.GetTable(Of vw_BT_Inv_Dtl)
		End Get
	End Property
	
	Public ReadOnly Property vw_WEB_Invoices() As System.Data.Linq.Table(Of vw_WEB_Invoice)
		Get
			Return Me.GetTable(Of vw_WEB_Invoice)
		End Get
	End Property
	
	<FunctionAttribute(Name:="dbo.HPB_CDC_DropShipments")>  _
	Public Function HPB_CDC_DropShipments(<Parameter(DbType:="NText")> ByVal xml As String, <Parameter(Name:="File", DbType:="VarChar(50)")> ByVal file As String) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), xml, file)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<FunctionAttribute(Name:="dbo.EDI_InvoiceHdrUpdStatus")>  _
	Public Function EDI_InvoiceHdrUpdStatus(<Parameter(Name:="InvoiceID", DbType:="Int")> ByVal invoiceID As System.Nullable(Of Integer), <Parameter(Name:="VendorID", DbType:="VarChar(20)")> ByVal vendorID As String) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), invoiceID, vendorID)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<FunctionAttribute(Name:="dbo.WEB_InvoiceHdrUpdStatus")>  _
	Public Function WEB_InvoiceHdrUpdStatus(<Parameter(Name:="InvoiceNo", DbType:="VarChar(20)")> ByVal invoiceNo As String, <Parameter(Name:="OrderNo", DbType:="VarChar(30)")> ByVal orderNo As String) As ISingleResult(Of WEB_InvoiceHdrUpdStatusResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), invoiceNo, orderNo)
		Return CType(result.ReturnValue,ISingleResult(Of WEB_InvoiceHdrUpdStatusResult))
	End Function
End Class

<Table(Name:="dbo.vw_BT_Inv_Hdr")>  _
Partial Public Class vw_BT_Inv_Hdr
	
	Private _InvoiceID As Integer
	
	Private _InvoiceNo As String
	
	Private _IssueDate As String
	
	Private _VendorID As String
	
	Private _PONumber As String
	
	Private _ReferenceNo As String
	
	Private _ShipToLoc As String
	
	Private _ShipToSAN As String
	
	Private _BillToLoc As String
	
	Private _BillToSAN As Char
	
	Private _ShipFromLoc As String
	
	Private _ShipFromSAN As String
	
	Private _TotalLines As System.Nullable(Of Integer)
	
	Private _TotalQty As System.Nullable(Of Integer)
	
	Private _TotalPayable As String
	
	Private _CurrencyCode As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Column(Storage:="_InvoiceID", DbType:="Int NOT NULL")>  _
	Public Property InvoiceID() As Integer
		Get
			Return Me._InvoiceID
		End Get
		Set
			If ((Me._InvoiceID = value)  _
						= false) Then
				Me._InvoiceID = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_InvoiceNo", DbType:="NVarChar(10)")>  _
	Public Property InvoiceNo() As String
		Get
			Return Me._InvoiceNo
		End Get
		Set
			If (String.Equals(Me._InvoiceNo, value) = false) Then
				Me._InvoiceNo = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_IssueDate", DbType:="NVarChar(8)")>  _
	Public Property IssueDate() As String
		Get
			Return Me._IssueDate
		End Get
		Set
			If (String.Equals(Me._IssueDate, value) = false) Then
				Me._IssueDate = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_VendorID", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property VendorID() As String
		Get
			Return Me._VendorID
		End Get
		Set
			If (String.Equals(Me._VendorID, value) = false) Then
				Me._VendorID = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_PONumber", DbType:="Char(6)")>  _
	Public Property PONumber() As String
		Get
			Return Me._PONumber
		End Get
		Set
			If (String.Equals(Me._PONumber, value) = false) Then
				Me._PONumber = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_ReferenceNo", DbType:="NVarChar(10)")>  _
	Public Property ReferenceNo() As String
		Get
			Return Me._ReferenceNo
		End Get
		Set
			If (String.Equals(Me._ReferenceNo, value) = false) Then
				Me._ReferenceNo = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_ShipToLoc", DbType:="Char(5)")>  _
	Public Property ShipToLoc() As String
		Get
			Return Me._ShipToLoc
		End Get
		Set
			If (String.Equals(Me._ShipToLoc, value) = false) Then
				Me._ShipToLoc = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_ShipToSAN", DbType:="NVarChar(21)")>  _
	Public Property ShipToSAN() As String
		Get
			Return Me._ShipToSAN
		End Get
		Set
			If (String.Equals(Me._ShipToSAN, value) = false) Then
				Me._ShipToSAN = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_BillToLoc", DbType:="VarChar(14) NOT NULL", CanBeNull:=false)>  _
	Public Property BillToLoc() As String
		Get
			Return Me._BillToLoc
		End Get
		Set
			If (String.Equals(Me._BillToLoc, value) = false) Then
				Me._BillToLoc = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_BillToSAN", DbType:="VarChar(1) NOT NULL")>  _
	Public Property BillToSAN() As Char
		Get
			Return Me._BillToSAN
		End Get
		Set
			If ((Me._BillToSAN = value)  _
						= false) Then
				Me._BillToSAN = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_ShipFromLoc", DbType:="NVarChar(7)")>  _
	Public Property ShipFromLoc() As String
		Get
			Return Me._ShipFromLoc
		End Get
		Set
			If (String.Equals(Me._ShipFromLoc, value) = false) Then
				Me._ShipFromLoc = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_ShipFromSAN", DbType:="NVarChar(12)")>  _
	Public Property ShipFromSAN() As String
		Get
			Return Me._ShipFromSAN
		End Get
		Set
			If (String.Equals(Me._ShipFromSAN, value) = false) Then
				Me._ShipFromSAN = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_TotalLines", DbType:="Int")>  _
	Public Property TotalLines() As System.Nullable(Of Integer)
		Get
			Return Me._TotalLines
		End Get
		Set
			If (Me._TotalLines.Equals(value) = false) Then
				Me._TotalLines = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_TotalQty", DbType:="Int")>  _
	Public Property TotalQty() As System.Nullable(Of Integer)
		Get
			Return Me._TotalQty
		End Get
		Set
			If (Me._TotalQty.Equals(value) = false) Then
				Me._TotalQty = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_TotalPayable", DbType:="NVarChar(30)")>  _
	Public Property TotalPayable() As String
		Get
			Return Me._TotalPayable
		End Get
		Set
			If (String.Equals(Me._TotalPayable, value) = false) Then
				Me._TotalPayable = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_CurrencyCode", DbType:="NChar(3)")>  _
	Public Property CurrencyCode() As String
		Get
			Return Me._CurrencyCode
		End Get
		Set
			If (String.Equals(Me._CurrencyCode, value) = false) Then
				Me._CurrencyCode = value
			End If
		End Set
	End Property
End Class

<Table(Name:="dbo.vw_BT_Inv_Dtl")>  _
Partial Public Class vw_BT_Inv_Dtl
	
	Private _ItemInvoiceID As Long
	
	Private _InvoiceID As Integer
	
	Private _LineNo As String
	
	Private _ItemIDCode As String
	
	Private _ItemIdentifier As String
	
	Private _ItemDesc As String
	
	Private _InvoiceQty As String
	
	Private _UnitPrice As String
	
	Private _DiscountPrice As String
	
	Private _DiscountCode As Char
	
	Private _DiscountPct As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Column(Storage:="_ItemInvoiceID", DbType:="BigInt NOT NULL")>  _
	Public Property ItemInvoiceID() As Long
		Get
			Return Me._ItemInvoiceID
		End Get
		Set
			If ((Me._ItemInvoiceID = value)  _
						= false) Then
				Me._ItemInvoiceID = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_InvoiceID", DbType:="Int NOT NULL")>  _
	Public Property InvoiceID() As Integer
		Get
			Return Me._InvoiceID
		End Get
		Set
			If ((Me._InvoiceID = value)  _
						= false) Then
				Me._InvoiceID = value
			End If
		End Set
	End Property
	
	<Column(Name:="[LineNo]", Storage:="_LineNo", DbType:="NVarChar(10)")>  _
	Public Property LineNo() As String
		Get
			Return Me._LineNo
		End Get
		Set
			If (String.Equals(Me._LineNo, value) = false) Then
				Me._LineNo = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_ItemIDCode", DbType:="NVarChar(10)")>  _
	Public Property ItemIDCode() As String
		Get
			Return Me._ItemIDCode
		End Get
		Set
			If (String.Equals(Me._ItemIDCode, value) = false) Then
				Me._ItemIDCode = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_ItemIdentifier", DbType:="NVarChar(15)")>  _
	Public Property ItemIdentifier() As String
		Get
			Return Me._ItemIdentifier
		End Get
		Set
			If (String.Equals(Me._ItemIdentifier, value) = false) Then
				Me._ItemIdentifier = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_ItemDesc", DbType:="NVarChar(100)")>  _
	Public Property ItemDesc() As String
		Get
			Return Me._ItemDesc
		End Get
		Set
			If (String.Equals(Me._ItemDesc, value) = false) Then
				Me._ItemDesc = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_InvoiceQty", DbType:="NVarChar(9)")>  _
	Public Property InvoiceQty() As String
		Get
			Return Me._InvoiceQty
		End Get
		Set
			If (String.Equals(Me._InvoiceQty, value) = false) Then
				Me._InvoiceQty = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_UnitPrice", DbType:="NVarChar(20)")>  _
	Public Property UnitPrice() As String
		Get
			Return Me._UnitPrice
		End Get
		Set
			If (String.Equals(Me._UnitPrice, value) = false) Then
				Me._UnitPrice = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_DiscountPrice", DbType:="NVarChar(20)")>  _
	Public Property DiscountPrice() As String
		Get
			Return Me._DiscountPrice
		End Get
		Set
			If (String.Equals(Me._DiscountPrice, value) = false) Then
				Me._DiscountPrice = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_DiscountCode", DbType:="VarChar(1) NOT NULL")>  _
	Public Property DiscountCode() As Char
		Get
			Return Me._DiscountCode
		End Get
		Set
			If ((Me._DiscountCode = value)  _
						= false) Then
				Me._DiscountCode = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_DiscountPct", DbType:="NVarChar(20)")>  _
	Public Property DiscountPct() As String
		Get
			Return Me._DiscountPct
		End Get
		Set
			If (String.Equals(Me._DiscountPct, value) = false) Then
				Me._DiscountPct = value
			End If
		End Set
	End Property
End Class

<Table(Name:="dbo.vw_WEB_Invoices")>  _
Partial Public Class vw_WEB_Invoice
	
	Private _InvoiceNumber As String
	
	Private _IssueDateTime As String
	
	Private _VendorID As String
	
	Private _OrderNumber As String
	
	Private _ASNNumber As String
	
	Private _ShipTo As String
	
	Private _TotalLines As Integer
	
	Private _InvoiceQuantity As String
	
	Private _TotalPayable As String
	
	Private _PurchaseAmount As System.Nullable(Of Decimal)
	
	Private _ShippingAmount As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Column(Storage:="_InvoiceNumber", DbType:="NVarChar(10)")>  _
	Public Property InvoiceNumber() As String
		Get
			Return Me._InvoiceNumber
		End Get
		Set
			If (String.Equals(Me._InvoiceNumber, value) = false) Then
				Me._InvoiceNumber = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_IssueDateTime", DbType:="VarChar(8000)")>  _
	Public Property IssueDateTime() As String
		Get
			Return Me._IssueDateTime
		End Get
		Set
			If (String.Equals(Me._IssueDateTime, value) = false) Then
				Me._IssueDateTime = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_VendorID", DbType:="NVarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property VendorID() As String
		Get
			Return Me._VendorID
		End Get
		Set
			If (String.Equals(Me._VendorID, value) = false) Then
				Me._VendorID = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_OrderNumber", DbType:="NVarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property OrderNumber() As String
		Get
			Return Me._OrderNumber
		End Get
		Set
			If (String.Equals(Me._OrderNumber, value) = false) Then
				Me._OrderNumber = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_ASNNumber", DbType:="NVarChar(13)")>  _
	Public Property ASNNumber() As String
		Get
			Return Me._ASNNumber
		End Get
		Set
			If (String.Equals(Me._ASNNumber, value) = false) Then
				Me._ASNNumber = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_ShipTo", DbType:="VarChar(30)")>  _
	Public Property ShipTo() As String
		Get
			Return Me._ShipTo
		End Get
		Set
			If (String.Equals(Me._ShipTo, value) = false) Then
				Me._ShipTo = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_TotalLines", DbType:="Int NOT NULL")>  _
	Public Property TotalLines() As Integer
		Get
			Return Me._TotalLines
		End Get
		Set
			If ((Me._TotalLines = value)  _
						= false) Then
				Me._TotalLines = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_InvoiceQuantity", DbType:="NVarChar(10)")>  _
	Public Property InvoiceQuantity() As String
		Get
			Return Me._InvoiceQuantity
		End Get
		Set
			If (String.Equals(Me._InvoiceQuantity, value) = false) Then
				Me._InvoiceQuantity = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_TotalPayable", DbType:="NVarChar(30)")>  _
	Public Property TotalPayable() As String
		Get
			Return Me._TotalPayable
		End Get
		Set
			If (String.Equals(Me._TotalPayable, value) = false) Then
				Me._TotalPayable = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_PurchaseAmount", DbType:="Money")>  _
	Public Property PurchaseAmount() As System.Nullable(Of Decimal)
		Get
			Return Me._PurchaseAmount
		End Get
		Set
			If (Me._PurchaseAmount.Equals(value) = false) Then
				Me._PurchaseAmount = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_ShippingAmount", DbType:="NVarChar(20)")>  _
	Public Property ShippingAmount() As String
		Get
			Return Me._ShippingAmount
		End Get
		Set
			If (String.Equals(Me._ShippingAmount, value) = false) Then
				Me._ShippingAmount = value
			End If
		End Set
	End Property
End Class

Partial Public Class WEB_InvoiceHdrUpdStatusResult
	
	Private _Column1 As Integer
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Column(Storage:="_Column1", DbType:="Int NOT NULL")>  _
	Public Property Column1() As Integer
		Get
			Return Me._Column1
		End Get
		Set
			If ((Me._Column1 = value)  _
						= false) Then
				Me._Column1 = value
			End If
		End Set
	End Property
End Class
