'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="ILS")>  _
Partial Public Class ILSDataDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.CDCData.My.MySettings.Default.ILSConnectionString2, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property vwItemBalance2Exports() As System.Data.Linq.Table(Of vwItemBalance2Export)
		Get
			Return Me.GetTable(Of vwItemBalance2Export)
		End Get
	End Property
	
	Public ReadOnly Property vwWEBItemSummaries() As System.Data.Linq.Table(Of vwWEBItemSummary)
		Get
			Return Me.GetTable(Of vwWEBItemSummary)
		End Get
	End Property
	
	Public ReadOnly Property vwReceipts2Exports() As System.Data.Linq.Table(Of vwReceipts2Export)
		Get
			Return Me.GetTable(Of vwReceipts2Export)
		End Get
	End Property
	
	Public ReadOnly Property vwReceiptDtls2Exports() As System.Data.Linq.Table(Of vwReceiptDtls2Export)
		Get
			Return Me.GetTable(Of vwReceiptDtls2Export)
		End Get
	End Property
	
	Public ReadOnly Property vwWEBItemsDetails() As System.Data.Linq.Table(Of vwWEBItemsDetail)
		Get
			Return Me.GetTable(Of vwWEBItemsDetail)
		End Get
	End Property
	
	Public ReadOnly Property vwHPBOrders2Exports() As System.Data.Linq.Table(Of vwHPBOrders2Export)
		Get
			Return Me.GetTable(Of vwHPBOrders2Export)
		End Get
	End Property
	
	Public ReadOnly Property vwHPBOrderDtls2Exports() As System.Data.Linq.Table(Of vwHPBOrderDtls2Export)
		Get
			Return Me.GetTable(Of vwHPBOrderDtls2Export)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.CDC_DeleteItemFromUploadTbl")>  _
	Public Function CDC_DeleteItemFromUploadTbl(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ItemNum", DbType:="VarChar(30)")> ByVal itemNum As String) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), itemNum)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.CDC_DeleteOrderFromUploadTbl")>  _
	Public Function CDC_DeleteOrderFromUploadTbl(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(30)")> ByVal erpNum As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal intfaceRecID As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal ordType As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(25)")> ByVal shipmentID As String) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), erpNum, intfaceRecID, ordType, shipmentID)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.CDC_DeleteReceiptFromUploadTbl")>  _
	Public Function CDC_DeleteReceiptFromUploadTbl(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal receiptLineNum As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(12)")> ByVal receiptID As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(4)")> ByVal procType As String) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), receiptLineNum, receiptID, procType)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.CDC_Interface_Shipment_Update")>  _
	Public Function CDC_Interface_Shipment_Update(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Decimal(9,0)")> ByVal shipNo As System.Nullable(Of Decimal)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), shipNo)
		Return CType(result.ReturnValue,Integer)
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vwItemBalance2Export")>  _
Partial Public Class vwItemBalance2Export
	
	Private _ITEM As String
	
	Private _COMPANY As String
	
	Private _ITEM_DESC As String
	
	Private _ISBN As String
	
	Private _ON_HAND_QTY As System.Nullable(Of Decimal)
	
	Private _ALLOCATED_QTY As System.Nullable(Of Decimal)
	
	Private _AVAILQTY As System.Nullable(Of Decimal)
	
	Private _QUANTITY_UM As String
	
	Private _WAREHOUSE As String
	
	Private _USER_STAMP As String
	
	Private _DATE_TIME_STAMP As Date
	
	Private _PROCESS_STAMP As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM", DbType:="NVarChar(25)")>  _
	Public Property ITEM() As String
		Get
			Return Me._ITEM
		End Get
		Set
			If (String.Equals(Me._ITEM, value) = false) Then
				Me._ITEM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMPANY", DbType:="NVarChar(25)")>  _
	Public Property COMPANY() As String
		Get
			Return Me._COMPANY
		End Get
		Set
			If (String.Equals(Me._COMPANY, value) = false) Then
				Me._COMPANY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM_DESC", DbType:="NVarChar(100)")>  _
	Public Property ITEM_DESC() As String
		Get
			Return Me._ITEM_DESC
		End Get
		Set
			If (String.Equals(Me._ITEM_DESC, value) = false) Then
				Me._ITEM_DESC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISBN", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property ISBN() As String
		Get
			Return Me._ISBN
		End Get
		Set
			If (String.Equals(Me._ISBN, value) = false) Then
				Me._ISBN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ON_HAND_QTY", DbType:="Decimal(19,5)")>  _
	Public Property ON_HAND_QTY() As System.Nullable(Of Decimal)
		Get
			Return Me._ON_HAND_QTY
		End Get
		Set
			If (Me._ON_HAND_QTY.Equals(value) = false) Then
				Me._ON_HAND_QTY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ALLOCATED_QTY", DbType:="Decimal(19,5)")>  _
	Public Property ALLOCATED_QTY() As System.Nullable(Of Decimal)
		Get
			Return Me._ALLOCATED_QTY
		End Get
		Set
			If (Me._ALLOCATED_QTY.Equals(value) = false) Then
				Me._ALLOCATED_QTY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AVAILQTY", DbType:="Decimal(20,5)")>  _
	Public Property AVAILQTY() As System.Nullable(Of Decimal)
		Get
			Return Me._AVAILQTY
		End Get
		Set
			If (Me._AVAILQTY.Equals(value) = false) Then
				Me._AVAILQTY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_QUANTITY_UM", DbType:="NVarChar(25)")>  _
	Public Property QUANTITY_UM() As String
		Get
			Return Me._QUANTITY_UM
		End Get
		Set
			If (String.Equals(Me._QUANTITY_UM, value) = false) Then
				Me._QUANTITY_UM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WAREHOUSE", DbType:="NVarChar(25)")>  _
	Public Property WAREHOUSE() As String
		Get
			Return Me._WAREHOUSE
		End Get
		Set
			If (String.Equals(Me._WAREHOUSE, value) = false) Then
				Me._WAREHOUSE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USER_STAMP", DbType:="NVarChar(30)")>  _
	Public Property USER_STAMP() As String
		Get
			Return Me._USER_STAMP
		End Get
		Set
			If (String.Equals(Me._USER_STAMP, value) = false) Then
				Me._USER_STAMP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DATE_TIME_STAMP", DbType:="DateTime NOT NULL")>  _
	Public Property DATE_TIME_STAMP() As Date
		Get
			Return Me._DATE_TIME_STAMP
		End Get
		Set
			If ((Me._DATE_TIME_STAMP = value)  _
						= false) Then
				Me._DATE_TIME_STAMP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PROCESS_STAMP", DbType:="NVarChar(100)")>  _
	Public Property PROCESS_STAMP() As String
		Get
			Return Me._PROCESS_STAMP
		End Get
		Set
			If (String.Equals(Me._PROCESS_STAMP, value) = false) Then
				Me._PROCESS_STAMP = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vwWEBItemSummary")>  _
Partial Public Class vwWEBItemSummary
	
	Private _ITEM As String
	
	Private _AvailableQty As System.Nullable(Of Integer)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM", DbType:="NVarChar(25)")>  _
	Public Property ITEM() As String
		Get
			Return Me._ITEM
		End Get
		Set
			If (String.Equals(Me._ITEM, value) = false) Then
				Me._ITEM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AvailableQty", DbType:="Int")>  _
	Public Property AvailableQty() As System.Nullable(Of Integer)
		Get
			Return Me._AvailableQty
		End Get
		Set
			If (Me._AvailableQty.Equals(value) = false) Then
				Me._AvailableQty = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vwReceipts2Export")>  _
Partial Public Class vwReceipts2Export
	
	Private _COMPANY As String
	
	Private _CARRIER As String
	
	Private _OrderType As String
	
	Private _RECEIPT_ID As String
	
	Private _PurchaseOrdNum As String
	
	Private _RECEIPT_TYPE As String
	
	Private _SHIP_FROM As String
	
	Private _SHIP_FROM_NAME As String
	
	Private _RECEIPT_ID_TYPE As String
	
	Private _WAREHOUSE As String
	
	Private _INTERNAL_RECEIPT_NUM As System.Nullable(Of Decimal)
	
	Private _ProcType As String
	
	Private _INVENTORY_STS As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMPANY", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property COMPANY() As String
		Get
			Return Me._COMPANY
		End Get
		Set
			If (String.Equals(Me._COMPANY, value) = false) Then
				Me._COMPANY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CARRIER", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property CARRIER() As String
		Get
			Return Me._CARRIER
		End Get
		Set
			If (String.Equals(Me._CARRIER, value) = false) Then
				Me._CARRIER = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderType", DbType:="NVarChar(50)")>  _
	Public Property OrderType() As String
		Get
			Return Me._OrderType
		End Get
		Set
			If (String.Equals(Me._OrderType, value) = false) Then
				Me._OrderType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RECEIPT_ID", DbType:="NVarChar(26)")>  _
	Public Property RECEIPT_ID() As String
		Get
			Return Me._RECEIPT_ID
		End Get
		Set
			If (String.Equals(Me._RECEIPT_ID, value) = false) Then
				Me._RECEIPT_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PurchaseOrdNum", DbType:="NVarChar(25)")>  _
	Public Property PurchaseOrdNum() As String
		Get
			Return Me._PurchaseOrdNum
		End Get
		Set
			If (String.Equals(Me._PurchaseOrdNum, value) = false) Then
				Me._PurchaseOrdNum = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RECEIPT_TYPE", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property RECEIPT_TYPE() As String
		Get
			Return Me._RECEIPT_TYPE
		End Get
		Set
			If (String.Equals(Me._RECEIPT_TYPE, value) = false) Then
				Me._RECEIPT_TYPE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_FROM", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIP_FROM() As String
		Get
			Return Me._SHIP_FROM
		End Get
		Set
			If (String.Equals(Me._SHIP_FROM, value) = false) Then
				Me._SHIP_FROM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_FROM_NAME", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIP_FROM_NAME() As String
		Get
			Return Me._SHIP_FROM_NAME
		End Get
		Set
			If (String.Equals(Me._SHIP_FROM_NAME, value) = false) Then
				Me._SHIP_FROM_NAME = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RECEIPT_ID_TYPE", DbType:="NVarChar(25)")>  _
	Public Property RECEIPT_ID_TYPE() As String
		Get
			Return Me._RECEIPT_ID_TYPE
		End Get
		Set
			If (String.Equals(Me._RECEIPT_ID_TYPE, value) = false) Then
				Me._RECEIPT_ID_TYPE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WAREHOUSE", DbType:="NVarChar(25)")>  _
	Public Property WAREHOUSE() As String
		Get
			Return Me._WAREHOUSE
		End Get
		Set
			If (String.Equals(Me._WAREHOUSE, value) = false) Then
				Me._WAREHOUSE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INTERNAL_RECEIPT_NUM", DbType:="Decimal(9,0)")>  _
	Public Property INTERNAL_RECEIPT_NUM() As System.Nullable(Of Decimal)
		Get
			Return Me._INTERNAL_RECEIPT_NUM
		End Get
		Set
			If (Me._INTERNAL_RECEIPT_NUM.Equals(value) = false) Then
				Me._INTERNAL_RECEIPT_NUM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProcType", DbType:="VarChar(2) NOT NULL", CanBeNull:=false)>  _
	Public Property ProcType() As String
		Get
			Return Me._ProcType
		End Get
		Set
			If (String.Equals(Me._ProcType, value) = false) Then
				Me._ProcType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INVENTORY_STS", DbType:="NVarChar(50)")>  _
	Public Property INVENTORY_STS() As String
		Get
			Return Me._INVENTORY_STS
		End Get
		Set
			If (String.Equals(Me._INVENTORY_STS, value) = false) Then
				Me._INVENTORY_STS = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vwReceiptDtls2Export")>  _
Partial Public Class vwReceiptDtls2Export
	
	Private _WAREHOUSE As String
	
	Private _COMPANY As String
	
	Private _ITEM As String
	
	Private _ITEM_DESC As String
	
	Private _ITEM_LIST_PRICE As System.Nullable(Of Decimal)
	
	Private _ITEM_NET_PRICE As System.Nullable(Of Decimal)
	
	Private _RECEIPT_ID As String
	
	Private _TOTAL_QTY As System.Nullable(Of Decimal)
	
	Private _GPItemNo As String
	
	Private _INVENTORY_STS As String
	
	Private _PURCHASE_ORDER_ID As String
	
	Private _PURCHASE_ORDER_LINE_NUMBER As System.Nullable(Of Decimal)
	
	Private _INTERNAL_RECEIPT_NUM As System.Nullable(Of Decimal)
	
	Private _ITEM_STYLE As String
	
	Private _ITEM_CATEGORY4 As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WAREHOUSE", DbType:="NVarChar(25)")>  _
	Public Property WAREHOUSE() As String
		Get
			Return Me._WAREHOUSE
		End Get
		Set
			If (String.Equals(Me._WAREHOUSE, value) = false) Then
				Me._WAREHOUSE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMPANY", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property COMPANY() As String
		Get
			Return Me._COMPANY
		End Get
		Set
			If (String.Equals(Me._COMPANY, value) = false) Then
				Me._COMPANY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM", DbType:="NVarChar(25)")>  _
	Public Property ITEM() As String
		Get
			Return Me._ITEM
		End Get
		Set
			If (String.Equals(Me._ITEM, value) = false) Then
				Me._ITEM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM_DESC", DbType:="NVarChar(100)")>  _
	Public Property ITEM_DESC() As String
		Get
			Return Me._ITEM_DESC
		End Get
		Set
			If (String.Equals(Me._ITEM_DESC, value) = false) Then
				Me._ITEM_DESC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM_LIST_PRICE", DbType:="Decimal(19,5)")>  _
	Public Property ITEM_LIST_PRICE() As System.Nullable(Of Decimal)
		Get
			Return Me._ITEM_LIST_PRICE
		End Get
		Set
			If (Me._ITEM_LIST_PRICE.Equals(value) = false) Then
				Me._ITEM_LIST_PRICE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM_NET_PRICE", DbType:="Decimal(19,5)")>  _
	Public Property ITEM_NET_PRICE() As System.Nullable(Of Decimal)
		Get
			Return Me._ITEM_NET_PRICE
		End Get
		Set
			If (Me._ITEM_NET_PRICE.Equals(value) = false) Then
				Me._ITEM_NET_PRICE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RECEIPT_ID", DbType:="NVarChar(26)")>  _
	Public Property RECEIPT_ID() As String
		Get
			Return Me._RECEIPT_ID
		End Get
		Set
			If (String.Equals(Me._RECEIPT_ID, value) = false) Then
				Me._RECEIPT_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TOTAL_QTY", DbType:="Decimal(38,5)")>  _
	Public Property TOTAL_QTY() As System.Nullable(Of Decimal)
		Get
			Return Me._TOTAL_QTY
		End Get
		Set
			If (Me._TOTAL_QTY.Equals(value) = false) Then
				Me._TOTAL_QTY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GPItemNo", DbType:="NVarChar(25)")>  _
	Public Property GPItemNo() As String
		Get
			Return Me._GPItemNo
		End Get
		Set
			If (String.Equals(Me._GPItemNo, value) = false) Then
				Me._GPItemNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INVENTORY_STS", DbType:="NVarChar(50)")>  _
	Public Property INVENTORY_STS() As String
		Get
			Return Me._INVENTORY_STS
		End Get
		Set
			If (String.Equals(Me._INVENTORY_STS, value) = false) Then
				Me._INVENTORY_STS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PURCHASE_ORDER_ID", DbType:="NVarChar(25)")>  _
	Public Property PURCHASE_ORDER_ID() As String
		Get
			Return Me._PURCHASE_ORDER_ID
		End Get
		Set
			If (String.Equals(Me._PURCHASE_ORDER_ID, value) = false) Then
				Me._PURCHASE_ORDER_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PURCHASE_ORDER_LINE_NUMBER", DbType:="Decimal(19,5)")>  _
	Public Property PURCHASE_ORDER_LINE_NUMBER() As System.Nullable(Of Decimal)
		Get
			Return Me._PURCHASE_ORDER_LINE_NUMBER
		End Get
		Set
			If (Me._PURCHASE_ORDER_LINE_NUMBER.Equals(value) = false) Then
				Me._PURCHASE_ORDER_LINE_NUMBER = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INTERNAL_RECEIPT_NUM", DbType:="Decimal(9,0)")>  _
	Public Property INTERNAL_RECEIPT_NUM() As System.Nullable(Of Decimal)
		Get
			Return Me._INTERNAL_RECEIPT_NUM
		End Get
		Set
			If (Me._INTERNAL_RECEIPT_NUM.Equals(value) = false) Then
				Me._INTERNAL_RECEIPT_NUM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM_STYLE", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property ITEM_STYLE() As String
		Get
			Return Me._ITEM_STYLE
		End Get
		Set
			If (String.Equals(Me._ITEM_STYLE, value) = false) Then
				Me._ITEM_STYLE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM_CATEGORY4", DbType:="NVarChar(50)")>  _
	Public Property ITEM_CATEGORY4() As String
		Get
			Return Me._ITEM_CATEGORY4
		End Get
		Set
			If (String.Equals(Me._ITEM_CATEGORY4, value) = false) Then
				Me._ITEM_CATEGORY4 = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vwWEBItemsDetail")>  _
Partial Public Class vwWEBItemsDetail
	
	Private _ITEM As String
	
	Private _ITEM_DESC As String
	
	Private _ISBN_UPC As String
	
	Private _Cost As System.Nullable(Of Decimal)
	
	Private _Price As System.Nullable(Of Decimal)
	
	Private _MSRP As System.Nullable(Of Decimal)
	
	Private _AvailableQty As Integer
	
	Private _BookType As String
	
	Private _Lenght As System.Nullable(Of Decimal)
	
	Private _Width As System.Nullable(Of Decimal)
	
	Private _Height As System.Nullable(Of Decimal)
	
	Private _Weight As System.Nullable(Of Decimal)
	
	Private _SectionCode As String
	
	Private _PublisherName As String
	
	Private _PubDate As Date
	
	Private _Author As String
	
	Private _Subtitle As String
	
	Private _NrOfPages As Short
	
	Private _BISACSubjectDesc As String
	
	Private _AcademicSubjectDesc As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM", DbType:="NVarChar(25)")>  _
	Public Property ITEM() As String
		Get
			Return Me._ITEM
		End Get
		Set
			If (String.Equals(Me._ITEM, value) = false) Then
				Me._ITEM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM_DESC", DbType:="NVarChar(100)")>  _
	Public Property ITEM_DESC() As String
		Get
			Return Me._ITEM_DESC
		End Get
		Set
			If (String.Equals(Me._ITEM_DESC, value) = false) Then
				Me._ITEM_DESC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[ISBN/UPC]", Storage:="_ISBN_UPC", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property ISBN_UPC() As String
		Get
			Return Me._ISBN_UPC
		End Get
		Set
			If (String.Equals(Me._ISBN_UPC, value) = false) Then
				Me._ISBN_UPC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Cost", DbType:="Money")>  _
	Public Property Cost() As System.Nullable(Of Decimal)
		Get
			Return Me._Cost
		End Get
		Set
			If (Me._Cost.Equals(value) = false) Then
				Me._Cost = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Price", DbType:="Money")>  _
	Public Property Price() As System.Nullable(Of Decimal)
		Get
			Return Me._Price
		End Get
		Set
			If (Me._Price.Equals(value) = false) Then
				Me._Price = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MSRP", DbType:="Money")>  _
	Public Property MSRP() As System.Nullable(Of Decimal)
		Get
			Return Me._MSRP
		End Get
		Set
			If (Me._MSRP.Equals(value) = false) Then
				Me._MSRP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AvailableQty", DbType:="Int NOT NULL")>  _
	Public Property AvailableQty() As Integer
		Get
			Return Me._AvailableQty
		End Get
		Set
			If ((Me._AvailableQty = value)  _
						= false) Then
				Me._AvailableQty = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BookType", DbType:="VarChar(9) NOT NULL", CanBeNull:=false)>  _
	Public Property BookType() As String
		Get
			Return Me._BookType
		End Get
		Set
			If (String.Equals(Me._BookType, value) = false) Then
				Me._BookType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Lenght", DbType:="Decimal(8,2)")>  _
	Public Property Lenght() As System.Nullable(Of Decimal)
		Get
			Return Me._Lenght
		End Get
		Set
			If (Me._Lenght.Equals(value) = false) Then
				Me._Lenght = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Width", DbType:="Decimal(8,2)")>  _
	Public Property Width() As System.Nullable(Of Decimal)
		Get
			Return Me._Width
		End Get
		Set
			If (Me._Width.Equals(value) = false) Then
				Me._Width = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Height", DbType:="Decimal(8,2)")>  _
	Public Property Height() As System.Nullable(Of Decimal)
		Get
			Return Me._Height
		End Get
		Set
			If (Me._Height.Equals(value) = false) Then
				Me._Height = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Weight", DbType:="Decimal(8,2)")>  _
	Public Property Weight() As System.Nullable(Of Decimal)
		Get
			Return Me._Weight
		End Get
		Set
			If (Me._Weight.Equals(value) = false) Then
				Me._Weight = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SectionCode", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property SectionCode() As String
		Get
			Return Me._SectionCode
		End Get
		Set
			If (String.Equals(Me._SectionCode, value) = false) Then
				Me._SectionCode = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PublisherName", DbType:="VarChar(80) NOT NULL", CanBeNull:=false)>  _
	Public Property PublisherName() As String
		Get
			Return Me._PublisherName
		End Get
		Set
			If (String.Equals(Me._PublisherName, value) = false) Then
				Me._PublisherName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PubDate", DbType:="SmallDateTime NOT NULL")>  _
	Public Property PubDate() As Date
		Get
			Return Me._PubDate
		End Get
		Set
			If ((Me._PubDate = value)  _
						= false) Then
				Me._PubDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Author", DbType:="VarChar(255) NOT NULL", CanBeNull:=false)>  _
	Public Property Author() As String
		Get
			Return Me._Author
		End Get
		Set
			If (String.Equals(Me._Author, value) = false) Then
				Me._Author = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Subtitle", DbType:="VarChar(150) NOT NULL", CanBeNull:=false)>  _
	Public Property Subtitle() As String
		Get
			Return Me._Subtitle
		End Get
		Set
			If (String.Equals(Me._Subtitle, value) = false) Then
				Me._Subtitle = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NrOfPages", DbType:="SmallInt NOT NULL")>  _
	Public Property NrOfPages() As Short
		Get
			Return Me._NrOfPages
		End Get
		Set
			If ((Me._NrOfPages = value)  _
						= false) Then
				Me._NrOfPages = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BISACSubjectDesc", DbType:="VarChar(80) NOT NULL", CanBeNull:=false)>  _
	Public Property BISACSubjectDesc() As String
		Get
			Return Me._BISACSubjectDesc
		End Get
		Set
			If (String.Equals(Me._BISACSubjectDesc, value) = false) Then
				Me._BISACSubjectDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AcademicSubjectDesc", DbType:="VarChar(80) NOT NULL", CanBeNull:=false)>  _
	Public Property AcademicSubjectDesc() As String
		Get
			Return Me._AcademicSubjectDesc
		End Get
		Set
			If (String.Equals(Me._AcademicSubjectDesc, value) = false) Then
				Me._AcademicSubjectDesc = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vwHPBOrders2Export")>  _
Partial Public Class vwHPBOrders2Export
	
	Private _COMPANY As String
	
	Private _CARRIER As String
	
	Private _ACTUAL_SHIP_DATE_TIME As System.Nullable(Of Date)
	
	Private _CUSTOMER As String
	
	Private _CUSTOMER_NAME As String
	
	Private _BOLNUM As String
	
	Private _PRONUM As String
	
	Private _SHIPMENT_ID As String
	
	Private _SHIPPING_LOAD_NUM As System.Nullable(Of Integer)
	
	Private _TOTAL_CONTAINERS As System.Nullable(Of Integer)
	
	Private _BoxCount As System.Nullable(Of Integer)
	
	Private _TOTAL_WEIGHT As Decimal
	
	Private _WAREHOUSE As String
	
	Private _CUSTOMER_PO As String
	
	Private _ERP_ORDER As String
	
	Private _BASE_FREIGHT_CHARGE As Decimal
	
	Private _TOTAL_FREIGHT_CHARGE As Decimal
	
	Private _INTERFACE_RECORD_ID As System.Nullable(Of Decimal)
	
	Private _ORDER_TYPE As String
	
	Private _SHIP_TO As String
	
	Private _SHIP_TO_ADDRESS1 As String
	
	Private _SHIP_TO_ADDRESS2 As String
	
	Private _SHIP_TO_ATTENTION_TO As String
	
	Private _SHIP_TO_CITY As String
	
	Private _SHIP_TO_COUNTRY As String
	
	Private _SHIP_TO_NAME As String
	
	Private _SHIP_TO_POSTAL_CODE As String
	
	Private _SHIP_TO_STATE As String
	
	Private _OrderType As String
	
	Private _GLAcct As String
	
	Private _InvAcct As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMPANY", DbType:="VarChar(3) NOT NULL", CanBeNull:=false)>  _
	Public Property COMPANY() As String
		Get
			Return Me._COMPANY
		End Get
		Set
			If (String.Equals(Me._COMPANY, value) = false) Then
				Me._COMPANY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CARRIER", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property CARRIER() As String
		Get
			Return Me._CARRIER
		End Get
		Set
			If (String.Equals(Me._CARRIER, value) = false) Then
				Me._CARRIER = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTUAL_SHIP_DATE_TIME", DbType:="DateTime")>  _
	Public Property ACTUAL_SHIP_DATE_TIME() As System.Nullable(Of Date)
		Get
			Return Me._ACTUAL_SHIP_DATE_TIME
		End Get
		Set
			If (Me._ACTUAL_SHIP_DATE_TIME.Equals(value) = false) Then
				Me._ACTUAL_SHIP_DATE_TIME = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CUSTOMER", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property CUSTOMER() As String
		Get
			Return Me._CUSTOMER
		End Get
		Set
			If (String.Equals(Me._CUSTOMER, value) = false) Then
				Me._CUSTOMER = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CUSTOMER_NAME", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property CUSTOMER_NAME() As String
		Get
			Return Me._CUSTOMER_NAME
		End Get
		Set
			If (String.Equals(Me._CUSTOMER_NAME, value) = false) Then
				Me._CUSTOMER_NAME = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BOLNUM", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property BOLNUM() As String
		Get
			Return Me._BOLNUM
		End Get
		Set
			If (String.Equals(Me._BOLNUM, value) = false) Then
				Me._BOLNUM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRONUM", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property PRONUM() As String
		Get
			Return Me._PRONUM
		End Get
		Set
			If (String.Equals(Me._PRONUM, value) = false) Then
				Me._PRONUM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIPMENT_ID", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIPMENT_ID() As String
		Get
			Return Me._SHIPMENT_ID
		End Get
		Set
			If (String.Equals(Me._SHIPMENT_ID, value) = false) Then
				Me._SHIPMENT_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIPPING_LOAD_NUM", DbType:="Int")>  _
	Public Property SHIPPING_LOAD_NUM() As System.Nullable(Of Integer)
		Get
			Return Me._SHIPPING_LOAD_NUM
		End Get
		Set
			If (Me._SHIPPING_LOAD_NUM.Equals(value) = false) Then
				Me._SHIPPING_LOAD_NUM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TOTAL_CONTAINERS", DbType:="Int")>  _
	Public Property TOTAL_CONTAINERS() As System.Nullable(Of Integer)
		Get
			Return Me._TOTAL_CONTAINERS
		End Get
		Set
			If (Me._TOTAL_CONTAINERS.Equals(value) = false) Then
				Me._TOTAL_CONTAINERS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BoxCount", DbType:="Int")>  _
	Public Property BoxCount() As System.Nullable(Of Integer)
		Get
			Return Me._BoxCount
		End Get
		Set
			If (Me._BoxCount.Equals(value) = false) Then
				Me._BoxCount = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TOTAL_WEIGHT", DbType:="Decimal(28,5) NOT NULL")>  _
	Public Property TOTAL_WEIGHT() As Decimal
		Get
			Return Me._TOTAL_WEIGHT
		End Get
		Set
			If ((Me._TOTAL_WEIGHT = value)  _
						= false) Then
				Me._TOTAL_WEIGHT = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WAREHOUSE", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property WAREHOUSE() As String
		Get
			Return Me._WAREHOUSE
		End Get
		Set
			If (String.Equals(Me._WAREHOUSE, value) = false) Then
				Me._WAREHOUSE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CUSTOMER_PO", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property CUSTOMER_PO() As String
		Get
			Return Me._CUSTOMER_PO
		End Get
		Set
			If (String.Equals(Me._CUSTOMER_PO, value) = false) Then
				Me._CUSTOMER_PO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ERP_ORDER", DbType:="NVarChar(25)")>  _
	Public Property ERP_ORDER() As String
		Get
			Return Me._ERP_ORDER
		End Get
		Set
			If (String.Equals(Me._ERP_ORDER, value) = false) Then
				Me._ERP_ORDER = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BASE_FREIGHT_CHARGE", DbType:="Decimal(19,5) NOT NULL")>  _
	Public Property BASE_FREIGHT_CHARGE() As Decimal
		Get
			Return Me._BASE_FREIGHT_CHARGE
		End Get
		Set
			If ((Me._BASE_FREIGHT_CHARGE = value)  _
						= false) Then
				Me._BASE_FREIGHT_CHARGE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TOTAL_FREIGHT_CHARGE", DbType:="Decimal(28,5) NOT NULL")>  _
	Public Property TOTAL_FREIGHT_CHARGE() As Decimal
		Get
			Return Me._TOTAL_FREIGHT_CHARGE
		End Get
		Set
			If ((Me._TOTAL_FREIGHT_CHARGE = value)  _
						= false) Then
				Me._TOTAL_FREIGHT_CHARGE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INTERFACE_RECORD_ID", DbType:="Decimal(18,0)")>  _
	Public Property INTERFACE_RECORD_ID() As System.Nullable(Of Decimal)
		Get
			Return Me._INTERFACE_RECORD_ID
		End Get
		Set
			If (Me._INTERFACE_RECORD_ID.Equals(value) = false) Then
				Me._INTERFACE_RECORD_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORDER_TYPE", DbType:="NVarChar(25)")>  _
	Public Property ORDER_TYPE() As String
		Get
			Return Me._ORDER_TYPE
		End Get
		Set
			If (String.Equals(Me._ORDER_TYPE, value) = false) Then
				Me._ORDER_TYPE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_TO", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIP_TO() As String
		Get
			Return Me._SHIP_TO
		End Get
		Set
			If (String.Equals(Me._SHIP_TO, value) = false) Then
				Me._SHIP_TO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_TO_ADDRESS1", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIP_TO_ADDRESS1() As String
		Get
			Return Me._SHIP_TO_ADDRESS1
		End Get
		Set
			If (String.Equals(Me._SHIP_TO_ADDRESS1, value) = false) Then
				Me._SHIP_TO_ADDRESS1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_TO_ADDRESS2", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIP_TO_ADDRESS2() As String
		Get
			Return Me._SHIP_TO_ADDRESS2
		End Get
		Set
			If (String.Equals(Me._SHIP_TO_ADDRESS2, value) = false) Then
				Me._SHIP_TO_ADDRESS2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_TO_ATTENTION_TO", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIP_TO_ATTENTION_TO() As String
		Get
			Return Me._SHIP_TO_ATTENTION_TO
		End Get
		Set
			If (String.Equals(Me._SHIP_TO_ATTENTION_TO, value) = false) Then
				Me._SHIP_TO_ATTENTION_TO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_TO_CITY", DbType:="NVarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIP_TO_CITY() As String
		Get
			Return Me._SHIP_TO_CITY
		End Get
		Set
			If (String.Equals(Me._SHIP_TO_CITY, value) = false) Then
				Me._SHIP_TO_CITY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_TO_COUNTRY", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIP_TO_COUNTRY() As String
		Get
			Return Me._SHIP_TO_COUNTRY
		End Get
		Set
			If (String.Equals(Me._SHIP_TO_COUNTRY, value) = false) Then
				Me._SHIP_TO_COUNTRY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_TO_NAME", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIP_TO_NAME() As String
		Get
			Return Me._SHIP_TO_NAME
		End Get
		Set
			If (String.Equals(Me._SHIP_TO_NAME, value) = false) Then
				Me._SHIP_TO_NAME = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_TO_POSTAL_CODE", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIP_TO_POSTAL_CODE() As String
		Get
			Return Me._SHIP_TO_POSTAL_CODE
		End Get
		Set
			If (String.Equals(Me._SHIP_TO_POSTAL_CODE, value) = false) Then
				Me._SHIP_TO_POSTAL_CODE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_TO_STATE", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property SHIP_TO_STATE() As String
		Get
			Return Me._SHIP_TO_STATE
		End Get
		Set
			If (String.Equals(Me._SHIP_TO_STATE, value) = false) Then
				Me._SHIP_TO_STATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderType", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property OrderType() As String
		Get
			Return Me._OrderType
		End Get
		Set
			If (String.Equals(Me._OrderType, value) = false) Then
				Me._OrderType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GLAcct", DbType:="NVarChar(250)")>  _
	Public Property GLAcct() As String
		Get
			Return Me._GLAcct
		End Get
		Set
			If (String.Equals(Me._GLAcct, value) = false) Then
				Me._GLAcct = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InvAcct", DbType:="NVarChar(250)")>  _
	Public Property InvAcct() As String
		Get
			Return Me._InvAcct
		End Get
		Set
			If (String.Equals(Me._InvAcct, value) = false) Then
				Me._InvAcct = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vwHPBOrderDtls2Export")>  _
Partial Public Class vwHPBOrderDtls2Export
	
	Private _ERP_ORDER As String
	
	Private _ERP_ORDER_LINE_NUM As System.Nullable(Of Decimal)
	
	Private _ITEM As String
	
	Private _ITEM_DESC As String
	
	Private _ITEM_NET_PRICE As System.Nullable(Of Decimal)
	
	Private _ITEM_LIST_PRICE As System.Nullable(Of Decimal)
	
	Private _ORDER_DATE As Date
	
	Private _ORDER_TYPE As String
	
	Private _SHIPMENT_ID As String
	
	Private _SHIPPED_QTY As System.Nullable(Of Decimal)
	
	Private _QUANTITY_UM As String
	
	Private _WAREHOUSE As String
	
	Private _GPItemNo As String
	
	Private _INTERFACE_LINK_ID As Decimal
	
	Private _TrackingNum As String
	
	Private _POLink As String
	
	Private _GLAcct As String
	
	Private _InvAcct As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ERP_ORDER", DbType:="NVarChar(25)")>  _
	Public Property ERP_ORDER() As String
		Get
			Return Me._ERP_ORDER
		End Get
		Set
			If (String.Equals(Me._ERP_ORDER, value) = false) Then
				Me._ERP_ORDER = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ERP_ORDER_LINE_NUM", DbType:="Decimal(19,5)")>  _
	Public Property ERP_ORDER_LINE_NUM() As System.Nullable(Of Decimal)
		Get
			Return Me._ERP_ORDER_LINE_NUM
		End Get
		Set
			If (Me._ERP_ORDER_LINE_NUM.Equals(value) = false) Then
				Me._ERP_ORDER_LINE_NUM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property ITEM() As String
		Get
			Return Me._ITEM
		End Get
		Set
			If (String.Equals(Me._ITEM, value) = false) Then
				Me._ITEM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM_DESC", DbType:="VarChar(70)")>  _
	Public Property ITEM_DESC() As String
		Get
			Return Me._ITEM_DESC
		End Get
		Set
			If (String.Equals(Me._ITEM_DESC, value) = false) Then
				Me._ITEM_DESC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM_NET_PRICE", DbType:="Decimal(12,2)")>  _
	Public Property ITEM_NET_PRICE() As System.Nullable(Of Decimal)
		Get
			Return Me._ITEM_NET_PRICE
		End Get
		Set
			If (Me._ITEM_NET_PRICE.Equals(value) = false) Then
				Me._ITEM_NET_PRICE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEM_LIST_PRICE", DbType:="Decimal(19,5)")>  _
	Public Property ITEM_LIST_PRICE() As System.Nullable(Of Decimal)
		Get
			Return Me._ITEM_LIST_PRICE
		End Get
		Set
			If (Me._ITEM_LIST_PRICE.Equals(value) = false) Then
				Me._ITEM_LIST_PRICE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORDER_DATE", DbType:="DateTime NOT NULL")>  _
	Public Property ORDER_DATE() As Date
		Get
			Return Me._ORDER_DATE
		End Get
		Set
			If ((Me._ORDER_DATE = value)  _
						= false) Then
				Me._ORDER_DATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORDER_TYPE", DbType:="NVarChar(25)")>  _
	Public Property ORDER_TYPE() As String
		Get
			Return Me._ORDER_TYPE
		End Get
		Set
			If (String.Equals(Me._ORDER_TYPE, value) = false) Then
				Me._ORDER_TYPE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIPMENT_ID", DbType:="NVarChar(25)")>  _
	Public Property SHIPMENT_ID() As String
		Get
			Return Me._SHIPMENT_ID
		End Get
		Set
			If (String.Equals(Me._SHIPMENT_ID, value) = false) Then
				Me._SHIPMENT_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIPPED_QTY", DbType:="Decimal(38,5)")>  _
	Public Property SHIPPED_QTY() As System.Nullable(Of Decimal)
		Get
			Return Me._SHIPPED_QTY
		End Get
		Set
			If (Me._SHIPPED_QTY.Equals(value) = false) Then
				Me._SHIPPED_QTY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_QUANTITY_UM", DbType:="NVarChar(25)")>  _
	Public Property QUANTITY_UM() As String
		Get
			Return Me._QUANTITY_UM
		End Get
		Set
			If (String.Equals(Me._QUANTITY_UM, value) = false) Then
				Me._QUANTITY_UM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WAREHOUSE", DbType:="NVarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property WAREHOUSE() As String
		Get
			Return Me._WAREHOUSE
		End Get
		Set
			If (String.Equals(Me._WAREHOUSE, value) = false) Then
				Me._WAREHOUSE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GPItemNo", DbType:="NVarChar(25)")>  _
	Public Property GPItemNo() As String
		Get
			Return Me._GPItemNo
		End Get
		Set
			If (String.Equals(Me._GPItemNo, value) = false) Then
				Me._GPItemNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INTERFACE_LINK_ID", DbType:="Decimal(9,0) NOT NULL")>  _
	Public Property INTERFACE_LINK_ID() As Decimal
		Get
			Return Me._INTERFACE_LINK_ID
		End Get
		Set
			If ((Me._INTERFACE_LINK_ID = value)  _
						= false) Then
				Me._INTERFACE_LINK_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TrackingNum", DbType:="VarChar(8000) NOT NULL", CanBeNull:=false)>  _
	Public Property TrackingNum() As String
		Get
			Return Me._TrackingNum
		End Get
		Set
			If (String.Equals(Me._TrackingNum, value) = false) Then
				Me._TrackingNum = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_POLink", DbType:="NVarChar(25)")>  _
	Public Property POLink() As String
		Get
			Return Me._POLink
		End Get
		Set
			If (String.Equals(Me._POLink, value) = false) Then
				Me._POLink = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GLAcct", DbType:="NVarChar(250)")>  _
	Public Property GLAcct() As String
		Get
			Return Me._GLAcct
		End Get
		Set
			If (String.Equals(Me._GLAcct, value) = false) Then
				Me._GLAcct = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InvAcct", DbType:="NVarChar(250)")>  _
	Public Property InvAcct() As String
		Get
			Return Me._InvAcct
		End Get
		Set
			If (String.Equals(Me._InvAcct, value) = false) Then
				Me._InvAcct = value
			End If
		End Set
	End Property
End Class
